# Site settings
title: /home/muammar/
email: muammar@muammar.me
description: "Muammar El Khatib" #> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://muammar.me" # the base hostname & protocol for your site
twitter_username: muammar
github_username:  muammar

# Build settings
markdown: kramdown

jekyll_compose:
    auto_open: true

permalink: /blog/:year/:month/:day/:title/

# blog

name: Muammar El Khatib's blog
